version: "3.9"

services:
  angular_app:
    build: .
    container_name: angular_client
    ports:
      - "4200:4200"
    command: ["npm", "run", "start", "--", "--host", "0.0.0.0"]
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped
