services:
  angular_app:
    build: .
    container_name: angular_client
    ports:
      - "4200:4200"
    volumes:
      - .:/app # optional: live reload
      - /app/node_modules
    restart: unless-stopped
